import { useState, useEffect, useRef } from 'react';
import API from '../services/api';
import { jsPDF } from "jspdf";
import ReactMarkdown from "react-markdown";

const ChatBot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [messages, setMessages] = useState([
    { text: "Ayubowan! 🙏 I am your Lak Assistant. How can I help you explore Sri Lanka today?", sender: "ai" }
  ]);
  const [chatHistory, setChatHistory] = useState([]); 
  const scrollRef = useRef();

  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  // --- Professional PDF Download Function ---
  const downloadPlan = (text) => {
    try {
      const doc = new jsPDF();
      const logoUrl = '/logo.png'; 

      doc.addImage(logoUrl, 'PNG', 15, 10, 25, 25); 
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(30, 64, 175); 
      doc.text("LAK TRAVELERS", 45, 22);
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.setFont("helvetica", "normal");
      doc.text("Your Trusted Sri Lankan Travel Partner", 45, 28);
      doc.text("www.laktravelers.com | info@laktravelers.com", 45, 33);

      doc.setDrawColor(30, 64, 175);
      doc.setLineWidth(0.5);
      doc.line(15, 40, 195, 40);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text("OFFICIAL TRAVEL ITINERARY", 15, 52);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      const splitText = doc.splitTextToSize(text, 170);
      doc.text(splitText, 15, 62);

      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Lak Assistant AI. © 2026 Lak Travelers.", 15, pageHeight - 12);
      
      doc.save("LakTravelers_TripPlan.pdf");
    } catch (err) {
      console.error("PDF Download Error:", err);
    }
  };

  const handleSend = async (e, quickText = null) => {
    if (e) e.preventDefault();
    const messageToSend = quickText || input;
    if (!messageToSend.trim()) return;

    setMessages(prev => [...prev, { text: messageToSend, sender: "user" }]);
    setInput("");
    setIsTyping(true);

    try {
      const { data } = await API.post('/ai/chat', { 
        message: messageToSend,
        history: chatHistory 
      });

      const aiReply = data.reply;
      setMessages(prev => [...prev, { text: aiReply, sender: "ai" }]);
      
      setChatHistory(prev => [
        ...prev,
        { role: "user", content: messageToSend },
        { role: "assistant", content: aiReply }
      ]);

    } catch (error) {
      setMessages(prev => [...prev, { text: "Ayubowan! 🙏 Sorry, a connection error occurred. Please try again.", sender: "ai" }]);
    } finally {
      setIsTyping(false);
    }
  };

  const shouldShowPDFButton = (messageText) => {
    const text = messageText.toLowerCase();
    const isLongEnough = text.length > 200;
    const hasTripKeywords = (text.includes("day 1") || text.includes("day 01")) && 
                           (text.includes("itinerary") || text.includes("morning") || text.includes("evening"));
    return isLongEnough && hasTripKeywords;
  };

  // --- ✨ AI Chat Message Custom Styling (Fixed Image Rendering) ---
  const ChatMarkdownStyles = {
    p: ({ children }) => <p className="mb-3 leading-relaxed">{children}</p>,
    strong: ({ children }) => <strong className="text-orange-600 font-black">✨ {children}</strong>,
    h3: ({ children }) => <h3 className="text-blue-600 font-bold mb-2 mt-2 flex items-center gap-1">📍 {children}</h3>,
    ul: ({ children }) => <ul className="list-disc ml-4 mb-3 space-y-1">{children}</ul>,
    ol: ({ children }) => <ol className="list-decimal ml-4 mb-3 space-y-1">{children}</ol>,
    li: ({ children }) => <li className="text-slate-700 font-medium">{children}</li>,
    
    // ✅ පින්තූර ගැටලුව විසඳන කොටස
    img: ({ src, alt }) => (
      <div className="my-4 overflow-hidden rounded-2xl border-2 border-slate-100 shadow-sm">
        <img 
          src={src} 
          alt={alt} 
          className="w-full h-auto object-cover hover:scale-105 transition-transform duration-500"
          onError={(e) => {
            e.target.onerror = null; 
            e.target.src="https://via.placeholder.com/400x250?text=Image+Loading...";
          }}
        />
      </div>
    ),
  };

  return (
    <div className="fixed bottom-6 right-6 z-[999]">
      {!isOpen && (
        <button 
          onClick={() => setIsOpen(true)} 
          className="bg-blue-600 p-5 rounded-full shadow-2xl hover:scale-110 transition-all duration-300 group"
        >
          <span className="text-white text-3xl group-hover:rotate-12 block">🤖</span>
        </button>
      )}

      {isOpen && (
        <div className="bg-white w-[420px] sm:w-[480px] h-[680px] rounded-[3rem] shadow-[0_25px_60px_rgba(0,0,0,0.25)] flex flex-col overflow-hidden border border-slate-100 animate-in slide-in-from-bottom-12 duration-500">
          
          <div className="bg-slate-900 p-6 text-white flex justify-between items-center shadow-lg">
            <div className="flex items-center gap-4">
              <div className="bg-blue-600 w-12 h-12 rounded-2xl flex items-center justify-center text-2xl border-2 border-slate-700 shadow-inner">🤖</div>
              <div>
                <h3 className="font-bold text-lg tracking-tight">Lak Assistant</h3>
                <p className="text-[10px] text-green-400 flex items-center gap-1.5 font-black uppercase tracking-widest">
                   Online Planner
                </p>
              </div>
            </div>
            <button onClick={() => setIsOpen(false)} className="hover:bg-slate-800 p-2.5 rounded-full transition-colors text-white">✕</button>
          </div>

          <div className="flex-grow p-6 overflow-y-auto space-y-6 bg-slate-50/50 scrollbar-hide">
            {messages.map((m, i) => (
              <div key={i} className={`flex flex-col ${m.sender === 'user' ? 'items-end' : 'items-start'} animate-in fade-in slide-in-from-bottom-2`}>
                <div className={`max-w-[88%] p-5 rounded-[2rem] text-sm shadow-sm leading-relaxed ${
                  m.sender === 'user' 
                  ? 'bg-blue-600 text-white rounded-br-none shadow-blue-100' 
                  : 'bg-white text-slate-800 border border-slate-100 rounded-bl-none shadow-sm'
                }`}>
                  <ReactMarkdown components={ChatMarkdownStyles}>
                    {m.text}
                  </ReactMarkdown>
                </div>
                
                {m.sender === 'ai' && shouldShowPDFButton(m.text) && (
                  <button 
                    onClick={() => downloadPlan(m.text)}
                    className="mt-4 flex items-center gap-2 bg-gradient-to-r from-emerald-600 to-teal-600 text-white px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:brightness-110 transition-all active:scale-95 shadow-lg shadow-emerald-100 group"
                  >
                    📄 DOWNLOAD FULL TRIP PLAN (PDF)
                  </button>
                )}
              </div>
            ))}
            
            {isTyping && (
              <div className="flex gap-2 ml-2 bg-white p-4 rounded-3xl shadow-sm border border-slate-100 w-20 justify-center items-center">
                <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce"></div>
                <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.5s]"></div>
              </div>
            )}
            <div ref={scrollRef}></div>
          </div>

          <div className="bg-white p-6 border-t border-slate-100">
            {messages.length === 1 && (
              <div className="flex gap-2 mb-4 overflow-x-auto pb-2 no-scrollbar">
                <button onClick={() => handleSend(null, "Plan a 3 day trip to Kandy")} className="whitespace-nowrap bg-blue-50 text-blue-600 border border-blue-100 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-tighter hover:bg-blue-100 transition-all shadow-sm">📍 3 Days Kandy</button>
                <button onClick={() => handleSend(null, "Show me best hotels in Ella")} className="whitespace-nowrap bg-blue-50 text-blue-600 border border-blue-100 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-tighter hover:bg-blue-100 transition-all shadow-sm">🏨 Hotels in Ella</button>
              </div>
            )}

            <form onSubmit={handleSend} className="flex gap-3">
              <input 
                value={input} 
                onChange={(e) => setInput(e.target.value)}
                placeholder="Where to next in Sri Lanka?" 
                className="flex-grow bg-slate-50 p-5 rounded-[1.5rem] border-2 border-transparent focus:border-blue-500/20 outline-none text-sm transition-all font-medium"
              />
              <button 
                type="submit" 
                disabled={!input.trim() || isTyping}
                className="bg-slate-900 hover:bg-blue-600 disabled:bg-slate-300 text-white w-14 h-14 rounded-2xl flex items-center justify-center transition-all shadow-xl active:scale-95"
              >
                <span className="text-xl">🚀</span>
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default ChatBot;